# Generated by Django 4.1 on 2022-09-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="ametities",
            new_name="amenities",
        ),
    ]
