# Generated by Django 4.1 on 2022-09-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perk",
            old_name="description",
            new_name="explanation",
        ),
    ]
